server:
  port: 9090
  error:
    whitelabel:
      enabled: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usersdatabase?useLegacyDatetimeCode=false&serverTimezone=CET
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

  thymeleaf:
    cache: false

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: cda3dc33209168d145bc
            client-secret: 053e27cbca3b9bd84c57d6d7433ce3ee59c27405

          google:
            clientId: 66637901374-0mmkb9pnnlgjvr2gus0ica4vj02ukggn.apps.googleusercontent.com
            clientSecret: klKuVc6eN2D-AGxNUES8fWde
            accessTokenUri: https://www.googleapis.com/oauth2/v3/token
            userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
            resource:
              userInfoUri: https://www.googleapis.com/plus/v1/people/me
            scope:
                - email
                - profile



  mail:
    host: smtp.gmail.com
    port: 587
    username: spirngcourseOPALKA@gmail.com
    password: SramPoKrzaczkach18!#
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true








