server:
  port: 9090
  error:
    whitelabel:
      enabled: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usersdatabase?useLegacyDatetimeCode=false&serverTimezone=CET
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

  thymeleaf:
    cache: false

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: *
            clientSecret: *
            accessTokenUri: https://www.googleapis.com/oauth2/v3/token
            userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
            resource:
              userInfoUri: https://www.googleapis.com/plus/v1/people/me
            scope:
                - email
                - profile



  mail:
    host: smtp.gmail.com
    port: 587
    username: *
    password: *
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true








